name: Build and Release

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "26"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload dist folder as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

      - name: Zip the build for release
        run: |
          cd dist
          zip -r "../MNT ${{ github.ref_name }}.zip" .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "MNT ${{ github.ref_name }}.zip"
          generate_release_notes: true
